"""Knowledge: extraction, chunking, retrieval and citations.

Extraction is tested against **real files** generated by the same libraries
people use to write them. A fixture made of hand-rolled bytes would only prove
the parser handles our idea of a PDF.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from jarvis.knowledge.chunk import TARGET_CHARS, chunk_blocks
from jarvis.knowledge.extract import (
    extract_html_document,
    extract_path,
    html_blocks,
)
from jarvis.knowledge.ingest import Ingestor, fingerprint
from jarvis.knowledge.models import Block, SourceKind, kind_for
from jarvis.knowledge.store import InMemoryKnowledgeStore, SqlKnowledgeStore
from jarvis.persistence.db import Database

# ── Real document fixtures ────────────────────────────────────────────────────


@pytest.fixture
def pdf_file(tmp_path: Path) -> Path:
    from pypdf import PdfWriter

    # pypdf cannot author text, so build a minimal but genuine PDF by hand and
    # let pypdf read it — the parser is what is under test.
    path = tmp_path / "report.pdf"
    pages = []
    for number, body in enumerate(
        ["Quarterly revenue reached 4.2 million dollars.", "Churn fell to 2.1 percent."], start=1
    ):
        stream = f"BT /F1 12 Tf 72 720 Td ({body}) Tj ET".encode()
        pages.append((number, stream))

    objects: list[bytes] = []
    kids = " ".join(f"{4 + i * 2} 0 R" for i in range(len(pages)))
    objects.append(b"<< /Type /Catalog /Pages 2 0 R >>")
    objects.append(f"<< /Type /Pages /Kids [{kids}] /Count {len(pages)} >>".encode())
    objects.append(b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>")
    for _, stream in pages:
        objects.append(
            f"<< /Type /Page /Parent 2 0 R /Resources << /Font << /F1 3 0 R >> >> "
            f"/MediaBox [0 0 612 792] /Contents {len(objects) + 2} 0 R >>".encode()
        )
        objects.append(f"<< /Length {len(stream)} >>\nstream\n".encode() + stream + b"\nendstream")

    out = bytearray(b"%PDF-1.4\n")
    offsets = []
    for index, body in enumerate(objects, start=1):
        offsets.append(len(out))
        out += f"{index} 0 obj\n".encode() + body + b"\nendobj\n"

    xref_at = len(out)
    out += f"xref\n0 {len(objects) + 1}\n".encode() + b"0000000000 65535 f \n"
    for offset in offsets:
        out += f"{offset:010d} 00000 n \n".encode()
    out += (
        f"trailer\n<< /Size {len(objects) + 1} /Root 1 0 R >>\nstartxref\n{xref_at}\n%%EOF".encode()
    )

    path.write_bytes(bytes(out))
    PdfWriter(clone_from=str(path))  # fails loudly if the file is not a real PDF
    return path


@pytest.fixture
def docx_file(tmp_path: Path) -> Path:
    import docx

    document = docx.Document()
    document.add_heading("Pricing Policy", level=1)
    document.add_paragraph("Standard plans renew annually at the listed rate.")
    document.add_heading("Discounts", level=2)
    document.add_paragraph("Annual prepayment receives fifteen percent off.")

    table = document.add_table(rows=2, cols=2)
    table.cell(0, 0).text = "Plan"
    table.cell(0, 1).text = "Price"
    table.cell(1, 0).text = "Pro"
    table.cell(1, 1).text = "49"

    path = tmp_path / "policy.docx"
    document.save(str(path))
    return path


@pytest.fixture
def pptx_file(tmp_path: Path) -> Path:
    from pptx import Presentation

    deck = Presentation()
    first = deck.slides.add_slide(deck.slide_layouts[1])
    first.shapes.title.text = "Growth Strategy"
    first.placeholders[1].text = "Enter the German market in Q3"

    second = deck.slides.add_slide(deck.slide_layouts[1])
    second.shapes.title.text = "Risks"
    second.placeholders[1].text = "Regulatory approval could slip"

    path = tmp_path / "strategy.pptx"
    deck.save(str(path))
    return path


@pytest.fixture
def xlsx_file(tmp_path: Path) -> Path:
    from openpyxl import Workbook

    workbook = Workbook()
    sheet = workbook.active
    sheet.title = "Revenue"
    sheet.append(["Month", "Amount"])
    sheet.append(["January", 120000])
    sheet.append(["February", 138000])

    second = workbook.create_sheet("Headcount")
    second.append(["Team", "People"])
    second.append(["Engineering", 12])

    path = tmp_path / "finances.xlsx"
    workbook.save(str(path))
    return path


# ── Extraction ────────────────────────────────────────────────────────────────


@pytest.mark.parametrize(
    ("suffix", "expected"),
    [
        (".pdf", SourceKind.PDF),
        (".md", SourceKind.MARKDOWN),
        (".PY", SourceKind.CODE),
        (".xlsx", SourceKind.XLSX),
        (".png", SourceKind.IMAGE),
        (".wat", SourceKind.UNKNOWN),
    ],
)
def test_suffixes_map_to_kinds(suffix: str, expected: SourceKind) -> None:
    assert kind_for(suffix) is expected


def test_pdf_pages_become_located_blocks(pdf_file: Path) -> None:
    extracted = extract_path(pdf_file)

    assert extracted.kind is SourceKind.PDF
    assert [b.locator for b in extracted.blocks] == ["p. 1", "p. 2"]
    assert "4.2 million" in extracted.blocks[0].text
    assert "Churn" in extracted.blocks[1].text


def test_docx_headings_become_locators_and_tables_survive(docx_file: Path) -> None:
    extracted = extract_path(docx_file)
    locators = {b.locator for b in extracted.blocks}

    assert "Pricing Policy" in locators
    assert "Discounts" in locators
    # The numbers people search for usually live in tables.
    table_block = next(b for b in extracted.blocks if b.locator.startswith("table"))
    assert "Pro | 49" in table_block.text


def test_pptx_slides_are_numbered(pptx_file: Path) -> None:
    extracted = extract_path(pptx_file)

    assert [b.locator for b in extracted.blocks] == ["slide 1", "slide 2"]
    assert "German market" in extracted.blocks[0].text
    assert extracted.metadata["slides"] == "2"


def test_xlsx_sheets_carry_cell_ranges(xlsx_file: Path) -> None:
    extracted = extract_path(xlsx_file)
    locators = [b.locator for b in extracted.blocks]

    assert any(loc.startswith("Revenue!") for loc in locators)
    assert any(loc.startswith("Headcount!") for loc in locators)
    assert "138000" in extracted.text


def test_markdown_sections_become_locators(tmp_path: Path) -> None:
    path = tmp_path / "notes.md"
    path.write_text(
        "# Roadmap\n\nIntro line.\n\n## Q3\n\nShip the API.\n\n## Q4\n\nHire two engineers."
    )

    extracted = extract_path(path)
    assert extracted.title == "Roadmap"
    assert {b.locator for b in extracted.blocks} == {"Roadmap", "Q3", "Q4"}


def test_code_blocks_cite_line_spans(tmp_path: Path) -> None:
    path = tmp_path / "service.py"
    path.write_text("\n".join(f"line_{i} = {i}" for i in range(200)))

    extracted = extract_path(path)
    assert extracted.kind is SourceKind.CODE
    assert extracted.blocks[0].locator == "lines 1–80"
    assert extracted.blocks[-1].locator.startswith("lines 161")


def test_csv_repeats_the_header_in_every_block(tmp_path: Path) -> None:
    path = tmp_path / "rows.csv"
    rows = ["name,amount"] + [f"customer{i},{i * 10}" for i in range(120)]
    path.write_text("\n".join(rows))

    extracted = extract_path(path)
    assert len(extracted.blocks) > 1
    # A row of numbers without its column names is unusable once retrieved.
    for block in extracted.blocks:
        assert block.text.startswith("name | amount")


def test_html_headings_become_locators_and_scripts_are_dropped() -> None:
    blocks = html_blocks(
        "<html><head><style>.a{color:red}</style></head><body>"
        "<h1>Terms</h1><p>Payment is due in 30 days.</p>"
        "<script>alert('x')</script><h2>Liability</h2><p>Capped at fees paid.</p>"
        "</body></html>"
    )
    assert [b.locator for b in blocks] == ["Terms", "Liability"]
    assert not any("alert" in b.text for b in blocks)
    assert "30 days" in blocks[0].text


def test_html_entities_are_decoded() -> None:
    blocks = html_blocks("<p>Tom &amp; Jerry &lt;3</p>")
    assert "Tom & Jerry <3" in blocks[0].text


def test_html_document_takes_its_title_from_the_tag() -> None:
    extracted = extract_html_document(
        "<title>Pricing — Acme</title><body><p>Plans start at $10.</p></body>",
        source="https://acme.test/pricing",
    )
    assert extracted.title == "Pricing — Acme"
    assert extracted.kind is SourceKind.URL


def test_an_unknown_suffix_is_read_as_text(tmp_path: Path) -> None:
    path = tmp_path / "Dockerfile"
    path.write_text("FROM python:3.11\n\nRUN pip install jarvis")

    extracted = extract_path(path)
    assert "python:3.11" in extracted.text


# ── Chunking ──────────────────────────────────────────────────────────────────


def test_small_blocks_are_packed_together() -> None:
    blocks = [Block(text=f"Paragraph {i}. " * 5, locator=f"p. {i}", order=i) for i in range(1, 4)]
    chunks = chunk_blocks(blocks)

    assert len(chunks) == 1
    # The locator must describe everything in the chunk, not just its first block.
    assert chunks[0].locator == "pp. 1–3"


def test_slides_get_their_own_range_form() -> None:
    blocks = [Block(text="x" * 100, locator=f"slide {i}", order=i) for i in range(1, 4)]
    assert chunk_blocks(blocks)[0].locator == "slides 1–3"


def test_mixed_locators_are_joined_honestly() -> None:
    blocks = [
        Block(text="a" * 100, locator="Overview", order=0),
        Block(text="b" * 100, locator="Risks", order=1),
    ]
    assert chunk_blocks(blocks)[0].locator == "Overview; Risks"


def test_an_oversized_block_is_split_with_part_numbers() -> None:
    """A citation must never claim more than the passage it points at."""
    huge = "\n\n".join(f"Paragraph {i}. " + "word " * 200 for i in range(12))
    chunks = chunk_blocks([Block(text=huge, locator="p. 7", order=0)])

    assert len(chunks) > 1
    assert all(c.locator.startswith("p. 7 (part ") for c in chunks)
    assert all(len(c.content) <= TARGET_CHARS + 400 for c in chunks)


def test_a_tiny_tail_joins_its_neighbour_rather_than_standing_alone() -> None:
    blocks = [
        Block(text="x" * (TARGET_CHARS - 100), locator="p. 1", order=0),
        Block(text="tiny", locator="p. 2", order=1),
    ]
    chunks = chunk_blocks(blocks)
    assert "tiny" in chunks[-1].content


def test_chunks_are_positioned_and_sized() -> None:
    blocks = [Block(text="word " * 400, locator=f"p. {i}", order=i) for i in range(1, 8)]
    chunks = chunk_blocks(blocks, document_id="doc_1")

    assert [c.position for c in chunks] == list(range(len(chunks)))
    assert all(c.document_id == "doc_1" for c in chunks)
    assert all(c.tokens > 0 for c in chunks)


def test_empty_input_produces_no_chunks() -> None:
    assert chunk_blocks([]) == []
    assert chunk_blocks([Block(text="   ", locator="p. 1")]) == []


# ── Retrieval and citations ───────────────────────────────────────────────────


@pytest.fixture(params=["memory", "sqlite"])
async def knowledge(request: pytest.FixtureRequest, tmp_path: Path, clock):
    """The same contract against both stores."""
    if request.param == "memory":
        yield InMemoryKnowledgeStore(clock=clock)
        return
    db = Database(f"sqlite+aiosqlite:///{tmp_path}/kb.db")
    await db.create_all()
    try:
        yield SqlKnowledgeStore(db, clock=clock)
    finally:
        await db.dispose()


async def test_ingesting_a_pdf_makes_it_searchable_with_a_page_citation(
    knowledge, pdf_file: Path
) -> None:
    result = await Ingestor(knowledge).ingest_file(pdf_file)
    assert len(result.documents) == 1

    citations = await knowledge.search("what was quarterly revenue")
    assert citations
    assert "4.2 million" in citations[0].snippet
    # Both pages are small enough to pack into one chunk, so the citation
    # covers the span it actually contains rather than only its first page.
    assert citations[0].locator == "pp. 1–2"
    assert citations[0].reference() == "report.pdf, pp. 1–2"


async def test_a_spreadsheet_is_searchable_by_its_numbers(knowledge, xlsx_file: Path) -> None:
    await Ingestor(knowledge).ingest_file(xlsx_file)
    citations = await knowledge.search("February revenue")

    assert citations
    assert "138000" in citations[0].snippet
    assert citations[0].locator.startswith("Revenue!")


async def test_citations_expose_the_signals_behind_them(knowledge, docx_file: Path) -> None:
    await Ingestor(knowledge).ingest_file(docx_file)
    citations = await knowledge.search("annual prepayment discount")

    assert citations
    assert set(citations[0].signals) == {"lexical", "semantic", "recency"}
    assert citations[0].score > 0


async def test_re_ingesting_unchanged_content_is_a_no_op(knowledge, docx_file: Path) -> None:
    ingestor = Ingestor(knowledge)
    first = await ingestor.ingest_file(docx_file)
    second = await ingestor.ingest_file(docx_file)

    assert len(first.documents) == 1
    assert second.documents == []
    assert second.unchanged  # reported, not silently ignored
    assert len(await knowledge.documents()) == 1


async def test_documents_can_be_removed_with_their_chunks(knowledge, pptx_file: Path) -> None:
    result = await Ingestor(knowledge).ingest_file(pptx_file)
    document = result.documents[0]

    assert await knowledge.remove(document.id) is True
    assert await knowledge.get(document.id) is None
    assert await knowledge.search("German market") == []
    assert await knowledge.remove(document.id) is False


async def test_search_can_be_confined_to_one_document(knowledge, pdf_file, docx_file) -> None:
    ingestor = Ingestor(knowledge)
    await ingestor.ingest_file(pdf_file)
    policy = (await ingestor.ingest_file(docx_file)).documents[0]

    citations = await knowledge.search("rate", document_id=policy.id)
    assert citations
    assert all(c.document_id == policy.id for c in citations)


async def test_scope_confines_retrieval(knowledge, docx_file, pptx_file) -> None:
    ingestor = Ingestor(knowledge)
    await ingestor.ingest_file(docx_file, scope="legal")
    await ingestor.ingest_file(pptx_file, scope="sales")

    citations = await knowledge.search("plan", scope="legal")
    assert all(c.source.endswith(".docx") for c in citations)


async def test_ingesting_a_directory_reads_what_it_can(knowledge, tmp_path: Path) -> None:
    folder = tmp_path / "project"
    (folder / ".git").mkdir(parents=True)
    (folder / ".git" / "config").write_text("should be skipped")
    (folder / "README.md").write_text("# Project\n\nIt does the thing.")
    (folder / "main.py").write_text("def run():\n    return 42\n")
    (folder / "logo.png").write_bytes(b"\x89PNG\r\n\x1a\n")

    result = await Ingestor(knowledge).ingest_directory(folder)
    titles = {d.title for d in result.documents}

    assert "Project" in titles
    assert "main.py" in titles
    # Skipped for a stated reason, rather than silently producing nothing.
    assert any("vision" in reason for reason in result.skipped.values())
    assert not any(".git" in source for source in result.skipped)


async def test_pasted_text_is_ingestable(knowledge) -> None:
    result = await Ingestor(knowledge).ingest_text(
        "The vendor contract renews on 1 March.\n\nNotice period is 60 days.",
        title="Contract notes",
    )
    assert result.documents[0].title == "Contract notes"

    citations = await knowledge.search("when does the vendor contract renew")
    assert "1 March" in citations[0].snippet


async def test_a_non_http_url_is_refused(knowledge) -> None:
    result = await Ingestor(knowledge).ingest_url("file:///etc/passwd")
    assert result.documents == []
    assert "only http" in result.skipped["file:///etc/passwd"]


async def test_a_url_is_ingested_with_its_title(knowledge, monkeypatch) -> None:
    import httpx

    def handler(request: httpx.Request) -> httpx.Response:
        return httpx.Response(
            200,
            text="<title>Acme Pricing</title><body><h1>Plans</h1><p>Pro is $49 a month.</p></body>",
        )

    transport = httpx.MockTransport(handler)
    original = httpx.AsyncClient
    monkeypatch.setattr(
        httpx, "AsyncClient", lambda *a, **k: original(*a, **{**k, "transport": transport})
    )

    result = await Ingestor(knowledge).ingest_url("https://acme.test/pricing")
    assert result.documents[0].title == "Acme Pricing"

    citations = await knowledge.search("how much is Pro")
    assert "$49" in citations[0].snippet
    assert citations[0].source == "https://acme.test/pricing"


async def test_search_on_an_empty_store_returns_nothing(knowledge) -> None:
    assert await knowledge.search("anything") == []


async def test_ingestion_publishes_an_event(clock) -> None:
    from jarvis.kernel.bus import EventBus

    bus = EventBus(clock=clock)
    store = InMemoryKnowledgeStore(bus=bus, clock=clock)
    sub = bus.subscribe("knowledge.**")

    await Ingestor(store).ingest_text("A note worth keeping.", title="Note")

    assert sub.queue.get_nowait().topic == "knowledge.ingested"


def test_fingerprints_are_content_addressed() -> None:
    assert fingerprint("same") == fingerprint("same")
    assert fingerprint("same") != fingerprint("different")


async def test_documents_survive_a_reconnect(tmp_path: Path, clock) -> None:
    url = f"sqlite+aiosqlite:///{tmp_path}/durable-kb.db"
    first = Database(url)
    await first.create_all()
    await Ingestor(SqlKnowledgeStore(first, clock=clock)).ingest_text(
        "The launch date is 12 September.", title="Launch"
    )
    await first.dispose()

    second = Database(url)
    citations = await SqlKnowledgeStore(second, clock=clock).search("when is launch")
    await second.dispose()

    assert citations and "12 September" in citations[0].snippet
