"""knowledge documents and chunks

Revision ID: 013ce7e29e25
Revises: 5bc9364681a5
Create Date: 2026-07-28 09:53:10.206036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import jarvis.persistence.models  # custom column types used by autogenerate
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '013ce7e29e25'
down_revision: Union[str, Sequence[str], None] = '5bc9364681a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('scope', sa.String(length=64), nullable=False),
    sa.Column('doc_metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('bytes', sa.Integer(), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_created_at'), 'documents', ['created_at'], unique=False)
    op.create_index(op.f('ix_documents_fingerprint'), 'documents', ['fingerprint'], unique=False)
    op.create_index(op.f('ix_documents_kind'), 'documents', ['kind'], unique=False)
    op.create_index(op.f('ix_documents_scope'), 'documents', ['scope'], unique=False)
    op.create_table('document_chunks',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('document_id', sa.String(length=64), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('locator', sa.String(length=255), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('tokens', sa.Integer(), nullable=False),
    sa.Column('embedding', jarvis.persistence.models.EmbeddingVector(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_chunks_document_id'), 'document_chunks', ['document_id'], unique=False)
    _create_chunk_vector_index()
    # ### end Alembic commands ###


def _create_chunk_vector_index() -> None:
    """HNSW index over chunk embeddings, matching the one on memories."""
    if op.get_bind().dialect.name != "postgresql":
        return
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_document_chunks_embedding_hnsw "
        "ON document_chunks USING hnsw (embedding vector_cosine_ops)"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_chunks_document_id'), table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index(op.f('ix_documents_scope'), table_name='documents')
    op.drop_index(op.f('ix_documents_kind'), table_name='documents')
    op.drop_index(op.f('ix_documents_fingerprint'), table_name='documents')
    op.drop_index(op.f('ix_documents_created_at'), table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
