"""trading department tables

Revision ID: 555b543682c0
Revises: 5e189e588419
Create Date: 2026-07-30 18:02:12.297132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import jarvis.persistence.models  # custom column types used by autogenerate
import jarvis.trading.database.models  # noqa: F401
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '555b543682c0'
down_revision: Union[str, Sequence[str], None] = '5e189e588419'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trading_market_snapshots',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('vix', sa.Float(), nullable=False),
    sa.Column('trend', sa.String(length=16), nullable=False),
    sa.Column('market_condition', sa.String(length=32), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trading_market_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trading_market_snapshots_timestamp'), ['timestamp'], unique=False)

    op.create_table('trading_options_snapshots',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('underlying', sa.String(length=16), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trading_options_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trading_options_snapshots_timestamp'), ['timestamp'], unique=False)

    op.create_table('trading_performance_metrics',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trading_performance_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trading_performance_metrics_computed_at'), ['computed_at'], unique=False)

    op.create_table('trading_signals',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('strategy_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('result', sa.String(length=16), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trading_signals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trading_signals_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_trading_signals_strategy_type'), ['strategy_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_trading_signals_timestamp'), ['timestamp'], unique=False)

    op.create_table('trading_users',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('telegram_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('settings', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trading_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trading_users_telegram_id'), ['telegram_id'], unique=True)

    op.create_table('trading_subscriptions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('tier', sa.String(length=32), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['trading_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trading_subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trading_subscriptions_user_id'), ['user_id'], unique=False)

    op.create_table('trading_trade_results',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('signal_id', sa.String(length=64), nullable=False),
    sa.Column('outcome', sa.String(length=16), nullable=False),
    sa.Column('pnl_usd', sa.Float(), nullable=False),
    sa.Column('pnl_pct', sa.Float(), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['signal_id'], ['trading_signals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trading_trade_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trading_trade_results_closed_at'), ['closed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_trading_trade_results_outcome'), ['outcome'], unique=False)
        batch_op.create_index(batch_op.f('ix_trading_trade_results_signal_id'), ['signal_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trading_trade_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trading_trade_results_signal_id'))
        batch_op.drop_index(batch_op.f('ix_trading_trade_results_outcome'))
        batch_op.drop_index(batch_op.f('ix_trading_trade_results_closed_at'))

    op.drop_table('trading_trade_results')
    with op.batch_alter_table('trading_subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trading_subscriptions_user_id'))

    op.drop_table('trading_subscriptions')
    with op.batch_alter_table('trading_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trading_users_telegram_id'))

    op.drop_table('trading_users')
    with op.batch_alter_table('trading_signals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trading_signals_timestamp'))
        batch_op.drop_index(batch_op.f('ix_trading_signals_strategy_type'))
        batch_op.drop_index(batch_op.f('ix_trading_signals_status'))

    op.drop_table('trading_signals')
    with op.batch_alter_table('trading_performance_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trading_performance_metrics_computed_at'))

    op.drop_table('trading_performance_metrics')
    with op.batch_alter_table('trading_options_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trading_options_snapshots_timestamp'))

    op.drop_table('trading_options_snapshots')
    with op.batch_alter_table('trading_market_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trading_market_snapshots_timestamp'))

    op.drop_table('trading_market_snapshots')
    # ### end Alembic commands ###
