"""vault, durable approvals and generated documents

Revision ID: 5e189e588419
Revises: f60aef9e3e09
Create Date: 2026-07-28 15:14:57.392342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import jarvis.persistence.models  # custom column types used by autogenerate
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5e189e588419'
down_revision: Union[str, Sequence[str], None] = 'f60aef9e3e09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approvals',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tool', sa.String(length=128), nullable=False),
    sa.Column('arguments', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=True),
    sa.Column('agent_id', sa.String(length=64), nullable=True),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('requested_at', sa.String(length=40), nullable=False),
    sa.Column('decided_at', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approvals_run_id'), 'approvals', ['run_id'], unique=False)
    op.create_index(op.f('ix_approvals_state'), 'approvals', ['state'], unique=False)
    op.create_index(op.f('ix_approvals_tool'), 'approvals', ['tool'], unique=False)
    op.create_table('generated_documents',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('mode', sa.String(length=32), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('body', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_documents_created_at'), 'generated_documents', ['created_at'], unique=False)
    op.create_index(op.f('ix_generated_documents_kind'), 'generated_documents', ['kind'], unique=False)
    op.create_index(op.f('ix_generated_documents_mode'), 'generated_documents', ['mode'], unique=False)
    op.create_table('secrets',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('blob', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('secrets')
    op.drop_index(op.f('ix_generated_documents_mode'), table_name='generated_documents')
    op.drop_index(op.f('ix_generated_documents_kind'), table_name='generated_documents')
    op.drop_index(op.f('ix_generated_documents_created_at'), table_name='generated_documents')
    op.drop_table('generated_documents')
    op.drop_index(op.f('ix_approvals_tool'), table_name='approvals')
    op.drop_index(op.f('ix_approvals_state'), table_name='approvals')
    op.drop_index(op.f('ix_approvals_run_id'), table_name='approvals')
    op.drop_table('approvals')
    # ### end Alembic commands ###
