"""workflows runs and triggers

Revision ID: f60aef9e3e09
Revises: 013ce7e29e25
Create Date: 2026-07-28 10:09:59.554658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import jarvis.persistence.models  # custom column types used by autogenerate
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f60aef9e3e09'
down_revision: Union[str, Sequence[str], None] = '013ce7e29e25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_runs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('workflow_id', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('cursor', sa.String(length=64), nullable=True),
    sa.Column('awaiting_approval_id', sa.String(length=64), nullable=True),
    sa.Column('snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_runs_awaiting_approval_id'), 'workflow_runs', ['awaiting_approval_id'], unique=False)
    op.create_index(op.f('ix_workflow_runs_created_at'), 'workflow_runs', ['created_at'], unique=False)
    op.create_index(op.f('ix_workflow_runs_state'), 'workflow_runs', ['state'], unique=False)
    op.create_index(op.f('ix_workflow_runs_workflow_id'), 'workflow_runs', ['workflow_id'], unique=False)
    op.create_table('workflow_triggers',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('workflow_id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('definition', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('last_fired_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_triggers_kind'), 'workflow_triggers', ['kind'], unique=False)
    op.create_index(op.f('ix_workflow_triggers_workflow_id'), 'workflow_triggers', ['workflow_id'], unique=False)
    op.create_table('workflows',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('definition', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workflows')
    op.drop_index(op.f('ix_workflow_triggers_workflow_id'), table_name='workflow_triggers')
    op.drop_index(op.f('ix_workflow_triggers_kind'), table_name='workflow_triggers')
    op.drop_table('workflow_triggers')
    op.drop_index(op.f('ix_workflow_runs_workflow_id'), table_name='workflow_runs')
    op.drop_index(op.f('ix_workflow_runs_state'), table_name='workflow_runs')
    op.drop_index(op.f('ix_workflow_runs_created_at'), table_name='workflow_runs')
    op.drop_index(op.f('ix_workflow_runs_awaiting_approval_id'), table_name='workflow_runs')
    op.drop_table('workflow_runs')
    # ### end Alembic commands ###
